### ISSUE TITLE
Fix scenario 3D models

### ISSUE THREAD

**Issue by leonifc331** [mogaika/god_of_war_browser#67]
- PS2
 - USA

**when I import a scenario model using a 3D program (blender or 3ds max) the model looks different from what appears in game**

**![2021-08-16](https://user-images.githubusercontent.com/37820098/129638519-e4f60119-8141-43f6-b6cd-41f7a411324a.png)t**

**Comment by mogaika** [comment]
Yep, not all of tricks regarding position calculation and object mapping from renderer implemented in exporter since I didn't know about them when I implemented it. One of the last discoveries regarding rotation/scaling I was able to find only last few weeks. Yep, will try to implement this soon, should not be hard now

**Comment by mogaika** [comment]
Fixed in gltf exporter
