### ISSUE TITLE
i can't repack ps2 gow2

### ISSUE THREAD

**Issue by vigneshvampire** [mogaika/god_of_war_browser#9]
i try lot of times i can't repack god of war 2 pak files,after change texture or 3d or changing name it not working after repack it freezed before title screen.. it's working fine for gow2 because i can't change single change in gow 2 why..any solution suggest me

**Comment by mogaika** [comment]
Thank you for report. GoW2 TOC file (Table of Content probably) marshaler was unimplemented for a long time after rewriting of virtual file system tree. Fixed in dev branch. You can download dev artifacts [here](https://ci.appveyor.com/project/mogaika/god-of-war-browser/branch/dev/artifacts)
Briefly tested on dvd9 ntfs version. In case of related problems reopen this issue
